services:
  mongodba:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Gabriel
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb_data:/data/db
